### ISSUE TITLE
Send_data issue from sadreal

### ISSUE THREAD

**Issue by raselmandol** [raselmandol/cryptobank#9]
Sad_real's request to check the temporary dump file security. I am opening this issue so that anyone can check that.
![Screenshot_problem_sendData](https://user-images.githubusercontent.com/130071257/231238254-79c7794a-77ab-429f-943d-24f039adeef0.png)

**Comment by sadreal** [comment]
also check problem2.
![prob2](https://user-images.githubusercontent.com/130279794/231238875-e904f083-d8d5-4ae4-81db-a8f4549e8a61.png)

**Comment by raselmandol** [comment]
I doubled checked the issu. Everythings working fine. closing the issue.
![working](https://user-images.githubusercontent.com/130071257/231239042-77ac36c8-898a-46d9-bbf0-151bc33c1c5b.png)
